### ISSUE TITLE
Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by haganbt** [gravityonmars/nodejs-starter#23]
Firstly, thanks for publishing this, I have already learnt a good deal by reading the code. Thank you for your time.

After a successful install - no errors, when I attempt to hit localhost:3000 the app crashes with the following exception as follows:

```
Failed to load c++ bson extension, using pure JS version
  njs:config Load local configuration from /Users/Ben/WebstormProjects/nodejs-starter/lib/config/development.json +0ms
  njs:config Merge environment set configuration variables +2ms
  njs:config Loaded config object for env development with sha "6cbfbb3f67bd7a46f14eb120de3b41d1" +2ms
  njs Application started on port 3000 +1s
/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:242
        throw message;      
              ^
Error: Error setting TTL index on collection : sessions
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/lib/connect-mongo.js:161:23
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1430:36
    at __executeInsertCommand (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1930:5)
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1427:14
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1560:7
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:162:16
    at commandHandler (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/cursor.js:706:16)
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/db.js:1806:9
    at Server.Base._callHandler (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)
    at /Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:485:18
    at MongoReply.parseBody (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:443:20)
    at emit (events.js:107:17)
    at null.<anonymous> (/Users/Ben/WebstormProjects/nodejs-starter/node_modules/connect-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:191:13)
    at emit (events.js:110:17)
make: *** [run] Error 1
Ben:nodejs-starter Ben$ 
```

My environment is as follows:
node: v0.12.4
mongodb-osx-x86_64-3.0.3
npm: 2.10.1

Appreciate any thoughts.

**Comment by haganbt** [comment]
Resolved by updating "connect-mongo" to  "0.8.2".
