### ISSUE TITLE
Failed to load c++ bson extension, using pure JS version

### ISSUE THREAD

**Issue by jotadepicas** [gravityonmars/nodejs-starter#25]
Hi, I've installed the project following the provided instructions, however when I try to run it I get the following messages:

```
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
```

It seems this is due to a build error in this module: `./node_modules/mongoose/node_modules/mongodb/node_modules/kerberos/builderror.log`

```
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:13:18: fatal error: util.h: No such file or directory
#include "util.h"
                 ^
compilation terminated.
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
```

So it seems this depends on a **missing header file util.h**.

My versions are as follows:
- node: v4.3.1
- node-gyp: v3.3.0

Am I doing something wrong or is this an actual bug? Why the missing util.h file? Is this due to versions compatibility? Let me know if you need more info.

Thanks!

**Comment by bwinterton** [comment]
+1 I am seeing this same issue. Specifically when running in the Node 4.4 docker container. I have installed build-essential, gcc, make, node-gyp, etc, but nothing seems to get me past this error.

**Comment by aresa7796** [comment]
+1

**Comment by aresa7796** [comment]
`
Failed to load c++ bson extension, using pure JS version
module.js:442
    throw err;
    ^

Error: Cannot find module 'lib/build'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at configuration (F:\node_space\nodejs-starter\lib\setup\index.js:41:13)
    at Object.<anonymous> (F:\node_space\nodejs-starter\lib\boot\index.js:31:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
`

**Comment by aresa7796** [comment]
`Failed to load c++ bson extension, using pure JS version
module.js:442
    throw err;
    ^

Error: Cannot find module 'lib/build'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at configuration (F:\node_space\nodejs-starter\lib\setup\index.js:41:13)
    at Object.<anonymous> (F:\node_space\nodejs-starter\lib\boot\index.js:31:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
`
